---
title: "Rasters and Cooling Centers"
author: "Tiffany Zhu"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(sf)
library(mapview)
library(mapboxapi)
library(leaflet)
library(leafem)
library(tigris)
library(raster)
library(fasterize)
library(stars)
library(googlesheets4)
setwd("/Users/tiffanyzhu/Documents/GitHub/climate/Tiffany/siting_by_addresses/Santa Clara County/")
```

# Data Loading

```{r import data}

# Addresses used to make big raster
geoms_to_plot = readRDS("geoms_to_plot.rds")

# Big raster
raster_geoms = readRDS("raster_geoms.rds")

# Cooling center data
gs4_deauth()
data <- 
range_speedread("1v7UwqTomNyX5V4dIlvHzq5_hHj28_mkFUyhx4d4MIXI") %>% 
  separate(
    Coordinates,
    into = c("Lat","Long"),
    sep = ","
  ) %>% 
  st_as_sf(coords = c("Long","Lat"), crs = '+proj=longlat +datum=WGS84')

```

# Create raster with addresses to remove

```{r get raster to subtract}

projection <- "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs" # EGPS 26910

# Addresses to drop
address_to_drop = readRDS("/Users/tiffanyzhu/Documents/GitHub/climate/Jing/Cooling Centers/addresses_within_walk.rds")
geoms_to_drop = geoms_to_plot %>%
  filter(LIMITED_ADDRESS %in% address_to_drop$LIMITED_ADDRESS) %>%
  mutate(neg_elderly = -1 * n_65_and_older_final) %>%
  st_transform(projection)

# Align bounding box of subtract geometries
# with bounding box of big raster
bigraster_bb = st_bbox(geoms_to_plot)
new_bb = c(bigraster_bb[1], bigraster_bb[2], bigraster_bb[3], bigraster_bb[4])
names(new_bb) = c("xmin", "ymin", "xmax", "ymax")
attr(new_bb, "class") = "bbox"
attr(st_geometry(geoms_to_drop), "bbox") = new_bb

# Generate subtract raster
subtract_raster = fasterize(geoms_to_drop, 
                            raster(geoms_to_drop, res = 200), 
                            field = "neg_elderly",
                            fun = "sum")
subtract_raster[is.na(subtract_raster[])] <- 0
saveRDS(subtract_raster, "subtract_raster.rds")

# Plot subtract raster
pal <- colorNumeric(c("#fde0dd", "#fa9fb5", "#c51b8a"),
                    values(subtract_raster),
                    na.color = "transparent")
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addRasterImage(subtract_raster,
                 colors = pal,
                 opacity = 0.6) %>%
  addLegend(pal = pal,
            values = values(subtract_raster),
            title = "Estimated Population<br>
                     Able to Access Area")

```

# Various tests

``` {r test raster subtraction, eval=F, include=F}

mini_raster <- fasterize(geoms_to_drop, 
                         raster(geoms_to_drop, res = 200), 
                         field = "n_65_and_older",
                         fun = "sum")

new_raster = mini_raster + subtract_raster
# Success
```

```{r plot mini raster, eval=F, include=F}

pal <- colorNumeric(c("#fde0dd", "#fa9fb5", "#c51b8a"),
                    values(mini_raster),
                    na.color = "transparent")
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addRasterImage(mini_raster,
                 colors = pal,
                 opacity = 0.6) %>%
  addLegend(pal = pal,
            values = values(mini_raster),
            title = "Estimated Population<br>
                     Able to Access Area")
```

```{r plot result of test subtraction, eval=F, include=F}

pal <- colorNumeric(c("#fde0dd", "#fa9fb5", "#c51b8a"),
                    values(new_raster),
                    na.color = "transparent")
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addRasterImage(new_raster,
                 colors = pal,
                 opacity = 0.6) %>%
  addLegend(pal = pal,
            values = values(new_raster),
            title = "Estimated Population<br>
                     Able to Access Area")

```

# Adjust map for existing cooling centers

```{r subtract from big raster}

# Raster subtraction
result = raster_geoms + subtract_raster
saveRDS(result, "result.rds")

# Adjust for miscellaneous negative values

# Get point geometries of subtracted addresses
# Uncomment only if number of subtracted addresses is small!
# subtract_geoms = addresses %>%
#   filter(LIMITED_ADDRESS %in% geoms_to_drop$LIMITED_ADDRESS) %>%
#   st_transform(4326)

# Plot result of subtraction
pal <- colorNumeric(c("#ffffff", "#fa9fb5", "#c51b8a"),
                    values(result),
                    na.color = "transparent")
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addRasterImage(result,
                 colors = pal,
                 opacity = 0.6) %>%
  addLegend(pal = pal,
            values = values(result),
            title = "Estimated Need in Area") %>%
  setView(lng = -121.90357379461862,
          lat = 37.284362741182556,
          zoom = 11)

```


# Original map for comparison

```{r plot original big raster for comparison}

pal <- colorNumeric(c("#ffffff", "#fa9fb5", "#c51b8a"),
                    values(raster_geoms),
                    na.color = "transparent")
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addRasterImage(raster_geoms,
                 colors = pal,
                 opacity = 0.6) %>%
  addLegend(pal = pal,
            values = values(raster_geoms),
            title = "Estimated Population<br>
                     Able to Access Area") %>%
  setView(lng = -121.90357379461862,
          lat = 37.284362741182556,
          zoom = 11)

```

# Original map with cooling center markers

```{r original big raster with markers}

pal <- colorNumeric(c("#ffffff", "#fa9fb5", "#c51b8a"),
                    values(raster_geoms),
                    na.color = "transparent")
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addRasterImage(raster_geoms,
                 colors = pal,
                 opacity = 0.6) %>%
  addMarkers(data = data,
             label = ~Name) %>%
  addLegend(pal = pal,
            values = values(raster_geoms),
            title = "Estimated Population<br>
                     Able to Access Area") %>%
  setView(lng = -121.90357379461862,
          lat = 37.284362741182556,
          zoom = 11)

```


