---
title: "Assigning Geometries to data within CA counties"
author: "Maggie"
date: "4/2/2021"
output: html_document
---
# this document was used to create the ZCTAs and the geom column used within the temperature dataframes.
# it can be used to gather ZCTAs in California that saw at least one heat incident in a given year.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, warning=FALSE,message=FALSE}
# icd is no longer in the CRAN repository
# https://cran.r-project.org/web/packages/icd/index.html
# you may not need to run these two package installs if the libraries already work on your own machine.
#install.packages("icd")
#install.packages("devtools")

# the following line was necessary on my machine to install icd correctly. 
#devtools::install_github("jackwasey/icd")
library(icd)
library(tidyverse)
library(sf)
library(tigris)
library(leaflet)
library(sp)
library(rgeos)
library(dplyr)
library(mapview)
```

Grabbing the data
```{r dataread}
#this pulls the optum summary data so we can grab the zipcodes of the relevant ZCTAs.

#each of the files below is a filtered version of the optum data that holds the health incidents
#as well as the zipcodes of each health incident on a month, year or season basis.

#since temperature data collection from rgee takes so long, we only want to look up temperature 
#values for ZCTAs that had at least one heat-related health instance in the relevant timeframe.

#in most events, we want the most ZCTAs with heat-related health incidents to be included. using "optum_summary_year" as our file will eventually us a list of each ZCTA that had a hospitalization in a year's time frame.
data <- readRDS("G:/Shared drives/SFBI-Restricted/PHS/optum_summary_year.rds")
#data_month <- readRDS("G:/Shared drives/SFBI-Restricted/PHS/optum_summary_month.rds")
#data_season <- readRDS("G:/Shared drives/SFBI-Restricted/PHS/optum_summary_season.rds")
```


```{r}
projection <- "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs" 

#grabbing the ZCTAS from tigris
# all california zipcodes start with "9x" where 0 <= x <- 6. 
# however, not all 9x zipcodes are CA zipcodes.
zipcodes<- zctas(cb = TRUE, starts_with = c("90", "91", "92", "93", "94", "95", "96"))
```

```{r echo=FALSE}
data_CA_all <- data %>% 
  filter(substr(ZIPCODE_5,1,2) %in% c("90", "91", "92", "93", "94", "95", "96")) %>% 

  #now filter to the ICD codes we are interested in
  filter(
    substr(DIAG, 1, 3) %in% c(
      "992", #specifically heat related
      "276",
      "994",
      "E87",
      "T73",
      "T67" #specifically heat related
    )
  )

# the following code block creates the geometries and formats the sf  
data_CA_all$geometry <- NA #create a new empty column where the geometry will go in
for (i in 1:nrow(data_CA_all)){
  #grab the first z1
  zcta <- str_split(data_CA_all$ZIPCODE_5[i], "_") %>% unlist() #split the zip codes
  zcta_geom <- zipcodes %>% filter(ZCTA5CE10 %in% zcta) #grabbing the geometry of the zctas from the bay area ZCTAs
  if(nrow(zcta_geom) > 0){ #if there is more than 0 in the dataframe then
    #grab the geometry
    zcta_geom <- zcta_geom %>% st_union() %>% st_cast("MULTIPOLYGON") #union/join the geometries together and make it a multipolygon
    data_CA_all$geometry[i] <- zcta_geom #assign it to the geometry column
  }
}
final <- data_CA_all %>% 
  st_as_sf() %>% #make the data a sf object
  st_set_crs(4269) %>% #assign it a coordinate reference system (crs)
  .[ca_counties %>% st_transform(projection) %>% st_buffer(-100) %>% st_transform(4269) ] 
```

```{r save_data}
#select whichever resolution you used to gather ZCTAs above. the file used will then be imported to rgee_CA.Rmd later.

#save data to google drive
saveRDS(final, "CA_year_ZCTAS_m.rds")
#saveRDS(final, "CA_month_ZCTAS_m.rds")
#saveRDS(final, "CA_season_ZCTAS_m.rds")

#read in the data after saving it to shared drive
#data_CA_month <- readRDS("G:/Shared drives/SFBI-Restricted/PHS/CA_month_ZCTAS_m.rds")
data_CA_year <- readRDS("G:/Shared drives/SFBI-Restricted/PHS/CA_year_ZCTAS_m.rds")
#data_CA_season <- readRDS("G:/Shared drives/SFBI-Restricted/PHS/CA_season_ZCTAS_m.rds")
```

